services:
  db:
    image: postgres:16
    container_name: rotransit-postgres
    restart: unless-stopped
    env_file:
      - ./db/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - rotransit_postgres_data:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  otp:
    build:
      context: ./otp
      dockerfile: Dockerfile
    container_name: otp
    restart: unless-stopped
    volumes:
      - ./otp:/var/opentripplanner
    environment:
      JAVA_OPTS: "-Xmx4G"
    command: --build --serve
    ports:
      - "8080:8080"

volumes:
  rotransit_postgres_data: