-- A city we serve, e.g. Brasov.
create TABLE city(
    id BIGINT GENERATED by default as identity primary key,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- A GTFS dataset served for a city (one transit network). The name is what the API calls companyName.
-- Deleting a city that still has feeds is refused (no cascade), so a typo can't wipe feeds and their history.
create TABLE feed(
    id BIGINT GENERATED by default as identity primary key,
    city_id BIGINT NOT NULL REFERENCES city(id),
    name VARCHAR(100) NOT NULL,
    UNIQUE (city_id, name)
);

-- Where a feed can be downloaded from. kind 'mobilitydb': ref is a Mobility Database id like 'mdb-2143';
-- kind 'url': ref is the download URL itself. priority 1 is tried first (trying the others comes later).
create TABLE feed_source(
    id BIGINT GENERATED by default as identity primary key,
    feed_id BIGINT NOT NULL REFERENCES feed(id) ON DELETE CASCADE,
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('mobilitydb', 'url')),
    ref VARCHAR(500) NOT NULL,
    priority INT NOT NULL DEFAULT 1,
    UNIQUE (feed_id, priority),
    UNIQUE (kind, ref)
);

-- One row per download attempt. A successful one has a file and becomes 'current' (the previous current
-- becomes 'old'); a failed one is stored as 'failed' with no file, so it never replaces the current version.
-- file_path is empty for failed attempts and for old versions whose file was deleted (retention keeps only the
-- current file plus one old one).
-- sha256 is NOT unique per feed on purpose: a feed can go back to an older file (version A, then B, then A again),
-- and that needs two rows with the same sha256. The same file on disk is shared by both rows.
create TABLE feed_version(
    id BIGINT GENERATED by default as identity primary key,
    feed_id BIGINT NOT NULL REFERENCES feed(id) ON DELETE CASCADE,
    source_id BIGINT REFERENCES feed_source(id) ON DELETE SET NULL,
    file_path VARCHAR(255),
    sha256 VARCHAR(64),
    starts_on DATE,
    expires_on DATE,
    downloaded_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('current', 'upcoming', 'old', 'failed'))
);
CREATE INDEX feed_version_feed_id_idx ON feed_version(feed_id);
-- safety net: the database itself refuses a second 'current' version for the same feed
CREATE UNIQUE INDEX feed_version_one_current_per_feed ON feed_version(feed_id) WHERE status = 'current';

-- The transit operators (agency.txt rows) inside one downloaded version.
-- TEXT because these values come from outside files and can be longer than we would guess.
create TABLE operator(
    id BIGINT GENERATED by default as identity primary key,
    feed_version_id BIGINT NOT NULL REFERENCES feed_version(id) ON DELETE CASCADE,
    agency_id TEXT,
    name TEXT NOT NULL,
    url TEXT
);
CREATE INDEX operator_feed_version_id_idx ON operator(feed_version_id);
